# Generated by Django 3.0.8 on 2020-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200817_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.AddField(
            model_name='user',
            name='uin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
