# Generated by Django 3.0.8 on 2020-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200818_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='type_test',
        ),
        migrations.AddField(
            model_name='history',
            name='subject1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='subject2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
