# Generated by Django 3.0.8 on 2020-08-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='variant',
        ),
        migrations.DeleteModel(
            name='test_variant',
        ),
    ]
