# Generated by Django 3.0.8 on 2020-07-15 11:36

from django.db import migrations, models
import django.db.models.deletion
import entapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('entapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='test',
            name='variants',
        ),
        migrations.AddField(
            model_name='testphoto',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_photo', to='entapp.Test'),
        ),
        migrations.AddField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_variant', to='entapp.Test'),
        ),
        migrations.AlterField(
            model_name='testphoto',
            name='photo',
            field=models.ImageField(upload_to=entapp.models.test_photos_dir),
        ),
    ]
