# Generated by Django 3.0.8 on 2020-07-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entapp', '0002_auto_20200715_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='test_variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='testphoto',
            name='test',
        ),
        migrations.AddField(
            model_name='testphoto',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_photo', to='entapp.Question'),
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='question_variant',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_variant', to='entapp.Question'),
        ),
        migrations.AddField(
            model_name='subject',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_test', to='entapp.test_variant'),
        ),
    ]
