# Generated by Django 3.0.8 on 2020-10-22 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_variant',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
