# Generated by Django 3.0.8 on 2020-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('subject_name', models.CharField(max_length=150)),
                ('card', models.CharField(max_length=150)),
            ],
        ),
    ]
