# Generated by Django 3.0.8 on 2020-09-23 17:06

from django.db import migrations, models
import online_course.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='avatar',
            field=models.ImageField(default='default/default.png', upload_to=online_course.models.tutor_photos_dir),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='experience',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
