# Generated by Django 3.0.8 on 2020-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0002_auto_20200923_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='type_cours',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
